language: node_js

cache: yarn

jobs:
  include:
    - stage: test
      script:
        - yarn check-types
        - yarn test
        - yarn check-formatting
    - stage: release
      deploy:
        - provider: npm
          api_key: $NPM_API_TOKEN
          on: 
            tags: true
        - provider: releases
          api_key: $GITHUB_API_TOKEN
          skip_cleanup: true
          on: 
            tags: true
