language: node_js
cache: yarn
script:
  - yarn check-types
  - yarn test
  - yarn check-formatting
deploy:
  - provider: npm
    skip_cleanup: true
    email: $NPM_API_EMAIL
    api_key: $NPM_API_TOKEN
    on: 
      tags: true
  - provider: releases
    api_key: $GITHUB_API_TOKEN
    on: 
      tags: true
