language: node_js
cache: yarn
jobs:
  include:
    - stage: tests
      script:
        - yarn check-types
        - yarn test
        - yarn check-formatting
    - stage: npm release
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        on: 
          tags: true
